"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import { ToasterProvider } from '../../providers/toast-provider'
import SessionProvider from '../../providers/session-provider'
import { ThemeProvider } from 'next-themes'
import { CartProvider } from '../../context/CartContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body className="dark:bg-zinc-950"> */}
      <body>
        <ThemeProvider attribute='class'>
          <SessionProvider>
            <ToasterProvider />
            <CartProvider>
              {children}
            </CartProvider>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
